### ISSUE TITLE
MQTT Topic for 'publish' is ignored - 'inverterControlLimit' used instead.

### ISSUE THREAD

**Issue by PaulSchulz** [longzheng/open-dynamic-export#69]
I used the following configuration for publishing to MQTT (in config/config.json)

"publish": {
    "mqtt": {
      "host": "mqtt://10.242.225.10",
      "username": "open-dynamic-export",
      "password": "open-dynamic-export",
      "topic": "open-dynamic-export/monitor"
    }
  }

The topic that the message is logged to is 'inverterControlLimit'

(It may be related, but can you check whether the MQTT topics that are being subscribed to for the MQTT limiter and MQTT site messages are also correct. My MQTT messages are not getting through to the status. eg. sending limiter message.)

**Comment by longzheng** [comment]
Whoops sorry my bad for trusting the Copilot generated code.

Fixed in https://github.com/longzheng/open-dynamic-export/releases/tag/v0.9.2-beta

Confirmed the MQTT limiter and MQTT meter are correct. Have a look in the Docker logs if there might be an error related to parsing the JSON message, if it fails it'll have an error "Invalid MQTT message" logged.

**Comment by PaulSchulz** [comment]
![Screenshot From 2024-12-13 20-13-06](https://github.com/user-attachments/assets/02bdef61-8815-4d1c-846e-8caa64b3cd77)

Working! Both publish and limiter.

**Comment by PaulSchulz** [comment]
Thanks
